all:
  children:

    routers:
      hosts:
        clab-network-lab-r1:
          ansible_connection: docker

    switches:
      hosts:
        clab-network-lab-sw1:
          ansible_connection: docker
        clab-network-lab-sw2:
          ansible_connection: docker

    hosts_group:
      hosts:
        clab-network-lab-pc1:
          ansible_connection: docker
        clab-network-lab-pc2:
          ansible_connection: docker
        clab-network-lab-pc3:
          ansible_connection: docker
        clab-network-lab-pc4:
          ansible_connection: docker
