global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:

  # Scrape Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Scrape cAdvisor for all container metrics
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    metrics_path: /metrics

  # Scrape the Docker host itself
  - job_name: 'docker'
    static_configs:
      - targets: ['172.17.0.1:9323']
